server:
  port: 8085

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/floop_order
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.floop.order.event.PaymentResultEvent

grpc:
  client:
    payment-service:
      address: ${PAYMENT_GRPC_URL:static://localhost:9091}
      negotiation-type: plaintext

resilience4j:
  circuitbreaker:
    instances:
      payment-service:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-calls-in-half-open-state: 2